{{- if .Values.configMap.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    {{- include "light-oauth2-code.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }} 