# Singleton service factory configuration/IoC injection
singletons:
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  - com.networknt.oauth.cache.CacheStartupHookProvider
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  - com.networknt.oauth.cache.CacheShutdownHookProvider

- com.networknt.oauth.auth.Authenticator<com.networknt.oauth.auth.DefaultAuth>:
  - com.networknt.oauth.auth.DefaultAuthenticator
- com.networknt.oauth.auth.Authenticator<com.networknt.oauth.auth.MarketPlaceAuth>:
  - com.networknt.oauth.auth.MarketPlaceAuthenticator
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: ${DB_URL:jdbc:mysql://localhost:3307/oauth2?useSSL=false&disableMariaDbDriver}
      username: ${DB_USERNAME:mysqluser}
      password: ${DB_PASSWORD:mysqlpw}
      maximumPoolSize: ${DB_MAX_POOL_SIZE:2}
      useServerPrepStmts: ${DB_USE_SERVER_PREP_STMTS:true}
      cachePrepStmts: ${DB_CACHE_PREP_STMTS:true}
      cacheCallableStmts: ${DB_CACHE_CALLABLE_STMTS:true}
      prepStmtCacheSize: ${DB_PREP_STMTS_CACHE_SIZE:4096}
      prepStmtCacheSqlLimit: ${DB_PREP_STMTS_CACHE_SQL_LIMIT:2048}
