# This file contains all the secrets for the server and client in order to manage and
# secure all of them in the same place. In Kubernetes, this file will be mapped to
# Secrets and all other config files will be mapped to mapConfig

---

# Sever section

# Key store password, the path of keystore is defined in server.yml
serverKeystorePass: ${SECRET_SERVER_KEYSTORE_PASS:password}

# Key password, the key is in keystore
serverKeyPass: ${SECRET_SERVER_KEY_PASS:password}

# Trust store password, the path of truststore is defined in server.yml
serverTruststorePass: ${SECRET_SERVER_TRUSTSTORE_PASS:password}


# Client section

# Key store password, the path of keystore is defined in server.yml
clientKeystorePass: ${SECRET_CLIENT_KEYSTORE_PASS:password}

# Key password, the key is in keystore
clientKeyPass: ${SECRET_CLIENT_KEY_PASS:password}

# Trust store password, the path of truststore is defined in server.yml
clientTruststorePass: ${SECRET_CLIENT_TRUSTSTORE_PASS:password}

# Authorization code client secret for OAuth2 server
authorizationCodeClientSecret: ${SECRET_AUTHORIZATION_CODE_CLIENT_SECRET:f6h1FTI8Q3-7UScPZDzfXA}

# Client credentials client secret for OAuth2 server
clientCredentialsClientSecret: ${SECRET_CLIENT_CREDENTIALS_CLIENT_SECRET:f6h1FTI8Q3-7UScPZDzfXA}

# Fresh token client secret for OAuth2 server
refreshTokenClientSecret: ${SECRET_REFRESH_TOKEN_CLIENT_SECRET:f6h1FTI8Q3-7UScPZDzfXA}

# Key distribution client secret for OAuth2 server
keyClientSecret: ${SECRET_KEY_CLIENT_SECRET:f6h1FTI8Q3-7UScPZDzfXA}

# Consul service registry and discovery

# Consul Token for service registry and discovery
# consulToken: the_one_ring

# EmailSender password
emailPassword: ${SECRET_EMAIL_PASSWORD:change-to-real-password}

# jwt private key password, used by light-oauth2 token and code services.
jwtPrivateKeyPassword: ${SECRET_JWT_PRIVATE_KEY_PASSWORD:password}
