# Server configuration
---
# This is the default binding address if the service is dockerized.
ip: ${SERVER_IP:0.0.0.0}

# Http port if enableHttp is true.
httpPort: ${SERVER_HTTP_PORT:6885}

# Enable HTTP should be false on official environment.
enableHttp: ${SERVER_ENABLE_HTTP:false}

# Https port if enableHttps is true.
httpsPort: ${SERVER_HTTPS_PORT:6885}

# Enable HTTPS should be true on official environment.
enableHttps: ${SERVER_ENABLE_HTTPS:true}

# Enable HTTP2 should be true on official environment.
enableHttp2: ${SERVER_ENABLE_HTTP2:true}

# Keystore file name in config folder. KeystorePass is in secret.yml to access it.
keystoreName: ${SERVER_KEYSTORE_NAME:server.keystore}

# Keystore password
keystorePass: ${SERVER_KEYSTORE_PASS:password}

# Private key password
keyPass: ${SERVER_KEY_PASS:password}

# Flag that indicate if two way TLS is enabled. Not recommended in docker container.
enableTwoWayTls: ${SERVER_ENABLE_TWO_WAY_TLS:false}

# Truststore file name in config folder. TruststorePass is in secret.yml to access it.
truststoreName: ${SERVER_TRUSTSTORE_NAME:server.truststore}

# Truststore password
truststorePass: ${SERVER_TRUSTSTORE_PASS:password}

# Unique service identifier. Used in service registration and discovery etc.
serviceId: ${SERVER_SERVICE_ID:com.networknt.oauth2-user-1.0.0}

# Flag to enable service registration. Only be true if running as standalone Java jar.
enableRegistry: ${SERVER_ENABLE_REGISTRY:false}

# environment tag that will be registered on consul to support multiple instances per env for testing.
# https://github.com/networknt/light-doc/blob/master/docs/content/design/env-segregation.md
# This tag should only be set for testing env, not production. The production certification process will enforce it.
# environment: test1
