environment: dev

image:
  repository: light-oauth2-oauth2-code
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "light-oauth2-code"
fullnameOverride: "light-oauth2-code"

config:
  enabled: false
  mountPath: "/config"
  files:
    # - client.keystore
    # - client.truststore
    # - primary.crt
    # - secondary.crt
    # - server.keystore
    # - server.truststore

secrets:
  enabled: true
  mountPath: "/config"
  files:
    - client.keystore
    - client.truststore
    - server.keystore
    - server.truststore
    - primary.crt
    - secondary.crt
    - cors.yml
    - github.yml
    - jwt.yml
    - ldap.yml
    - logback.xml
    - oauth_code.yml
    - openapi-validator.yml
    - openapi.yaml
    - secret.yml
    - security.yml
    - server.yml
    - service.yml
    - spnego.yml

volumes:
  # - name: config-volume
  #   configMap:
  #     name: light-oauth2-code-config
  - name: secret-volume
    secret:
      secretName: light-oauth2-code-secret

volumeMounts:
  # - name: config-volume
  #   mountPath: "/config"
  - name: secret-volume
    mountPath: "/config"