uri: ${LDAP_URI:ldaps://localhost:10636/ou=users,dc=undertow,dc=io}
domain: ${LDAP_DOMAIN:undertow.io}
ldapPrincipal: ${LDAP_PRINCIPAL:uid=oauth,ou=users,dc=undertow,dc=io}
searchFilter: ${LDAP_SEARCH_FILTER:(&(uid=%s)(objectClass=person))}
searchBase: ${LDAP_SEARCH_BASE:''}