# This file contains all the secrets for the server and client in order to manage and
# secure all of them in the same place. In Kubernetes, this file will be mapped to
# Secrets and all other config files will be mapped to mapConfig

---

# Sever section

# Key store password, the path of keystore is defined in server.yml
serverKeystorePass: ${SERVER_KEYSTORE_PASS:password}

# Key password, the key is in keystore
serverKeyPass: ${SERVER_KEY_PASS:password}

# Trust store password, the path of truststore is defined in server.yml
serverTruststorePass: ${SERVER_TRUSTSTORE_PASS:password}


# Client section

# Key store password, the path of keystore is defined in server.yml
clientKeystorePass: ${CLIENT_KEYSTORE_PASS:password}

# Key password, the key is in keystore
clientKeyPass: ${CLIENT_KEY_PASS:password}

# Trust store password, the path of truststore is defined in server.yml
clientTruststorePass: ${CLIENT_TRUSTSTORE_PASS:password}

# Authorization code client secret for OAuth2 server
authorizationCodeClientSecret: ${AUTHORIZATION_CODE_CLIENT_SECRET:f6h1FTI8Q3-7UScPZDzfXA}

# Client credentials client secret for OAuth2 server
clientCredentialsClientSecret: ${CLIENT_CREDENTIALS_CLIENT_SECRET:f6h1FTI8Q3-7UScPZDzfXA}

# Key distribution client secret for OAuth2 server
keyClientSecret: ${KEY_CLIENT_SECRET:f6h1FTI8Q3-7UScPZDzfXA}


# Consul service registry and discovery

# Consul Token for service registry and discovery
# consulToken: ${CONSUL_TOKEN:the_one_ring}

# EmailSender password
emailPassword: ${EMAIL_PASSWORD:change-to-real-password}

# jwt private key password, used by light-oauth2 token and code services.
jwtPrivateKeyPassword: ${JWT_PRIVATE_KEY_PASSWORD:password}

# LDAP credentials
ladpCredential: ${LDAP_CREDENTIAL:theoauth}

# Github API token
githubToken: ${GITHUB_TOKEN:githubToken}

# SPNEGO/Kerberos SPN password
spnegoServicePassword: ${SPNEGO_SERVICE_PASSWORD:servicepwd}