{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "light-oauth2-code.fullname" . }}-secret
  labels:
    {{- include "light-oauth2-code.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $env := .Values.environment }}
  {{- range $file := .Values.secrets.files }}
  {{ $file }}: |-
    {{- $.Files.Get (printf "config/%s/%s" $env $file) | b64enc | nindent 4 }}
  {{- end }}
{{- end }}